### PR TITLE
add `disrcod.com`

### PR DESCRIPTION
**Pull request by Xaliks**

### CODE REVIEW

**Comment by Tegnio** [comment]
Thanks for your contribution!

**Comment by tovade** [comment]
stolen and no credits D: ban pls

**Comment by Tegnio** [comment]
> stolen and no credits D: ban pls

Where it is stolen from?

**Comment by tovade** [comment]
https://ptb.discord.com/channels/737006392078106786/738344228391878717/871303234743042058

**Comment by Tegnio** [comment]
Despite the fact that you uploaded a screenshot, I still don't think I need to issue a ban. I also sometimes find other people's screenshots with malicious links and just add them to the filter. What's wrong with that? 🤔

**Pull request merged**
